# How to author Executors: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
description: >
  A Docker container that can be used to run lein nvd check.
docker:
  - image: 'circleci/clojure:<<parameters.tag>>'
parameters:
  tag:
    default: latest
    description: >
      Variant of circleci/clojure image to use:
      http://hub.docker.com/r/circleci/clojure/tags
    type: string
