# How to author Executors: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
description: >
  A Docker container that can be used to run lein nvd check.
docker:
  - image: 'cimg/clojure:<<parameters.tag>>'
parameters:
  tag:
    default: "1.10"
    description: |
      Select an available tag here:
      https://hub.docker.com/r/cimg/clojure/tags
    type: string
